fix again

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -30,76 +30,76 @@ env:
   TF_APPEND_USER_AGENT: pulumi
 
 jobs:
-  #publish:
-  #  name: publish
-  #  runs-on: ubuntu-latest
-  #  steps:
-  #  - name: Validate prerelease
-  #    if: inputs.isPrerelease == false && (contains(inputs.version, '-') || contains(inputs.version, '+'))
-  #    run: echo "Can't publish a prerelease version as a stable release. This is likely a bug in the calling workflow." && exit 1
-  #  - name: Validate skipGoSdk
-  #    if: inputs.skipGoSdk && inputs.isPrerelease == false
-  #    run: echo "Can't skip Go SDK for stable releases. This is likely a bug in the calling workflow." && exit 1
-  #  - name: Checkout Repo
-  #    uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
-  #    with:
-  #      persist-credentials: false
-  #      submodules: true
-  #  - name: Setup mise
-  #    uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5
-  #    env:
-  #      MISE_FETCH_REMOTE_VERSIONS_TIMEOUT: 30s
-  #    with:
-  #      version: 2026.2.15
-  #      cache_save: false
-  #  - name: Create dist directory
-  #    run: mkdir -p dist
-  #  - name: Download provider assets
-  #    uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
-  #    with:
-  #      pattern: pulumi-resource-xyz-v${{ inputs.version }}-*
-  #      path: dist
-  #      # Don't create a directory for each artifact
-  #      merge-multiple: true
-  #  - name: Download schema
-  #    uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
-  #    with:
-  #      # Use a pattern to avoid failing if the artifact doesn't exist
-  #      pattern: schema-embed.*
-  #      # Avoid creating directories for each artifact
-  #      merge-multiple: true
-  #      path: dist
-  #  - name: Calculate checksums
-  #    working-directory: dist
-  #    run: shasum ./*.tar.gz > "pulumi-xyz_${{ inputs.version }}_checksums.txt"
-  #  - name: Get Schema Change Summary
-  #    id: schema-summary
-  #    shell: bash
-  #    run: |
-  #      # Get latest stable release. Return only first column from result (tag).
-  #      LAST_VERSION=$(gh release view --repo pulumi/pulumi-xyz --json tagName -q .tagName || echo "No stable release" )
-  #      {
-  #        echo 'summary<<EOF'
-  #        if [[ "$LAST_VERSION" != "No stable release" ]]; then
-  #          schema-tools compare --provider="xyz" --old-commit="$LAST_VERSION" --repository="github://api.github.com/pulumi" --new-commit="--local-path=provider/cmd/pulumi-resource-xyz/schema.json"
-  #        fi
-  #        echo 'EOF'
-  #      } >> "$GITHUB_OUTPUT"
-  #  - name: Create GH Release
-  #    uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
-  #    if: inputs.isPrerelease == false
-  #    with:
-  #      tag_name: v${{ inputs.version }}
-  #      prerelease: ${{ inputs.isPrerelease }}
-  #      # We keep pre-releases as drafts so they're not visible until we manually publish them.
-  #      draft: ${{ inputs.isPrerelease }}
-  #      # Explicitly set make_latest to account for backported releases
-  #      make_latest: ${{ inputs.setLatestRelease }}
-  #      body: ${{ steps.schema-summary.outputs.summary }}
-  #      generate_release_notes: true
-  #      files: dist/*
-  #    env:
-  #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  publish:
+    name: publish
+    runs-on: ubuntu-latest
+    steps:
+    - name: Validate prerelease
+      if: inputs.isPrerelease == false && (contains(inputs.version, '-') || contains(inputs.version, '+'))
+      run: echo "Can't publish a prerelease version as a stable release. This is likely a bug in the calling workflow." && exit 1
+    - name: Validate skipGoSdk
+      if: inputs.skipGoSdk && inputs.isPrerelease == false
+      run: echo "Can't skip Go SDK for stable releases. This is likely a bug in the calling workflow." && exit 1
+    - name: Checkout Repo
+      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+      with:
+        persist-credentials: false
+        submodules: true
+    - name: Setup mise
+      uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5
+      env:
+        MISE_FETCH_REMOTE_VERSIONS_TIMEOUT: 30s
+      with:
+        version: 2026.2.15
+        cache_save: false
+    - name: Create dist directory
+      run: mkdir -p dist
+    - name: Download provider assets
+      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
+      with:
+        pattern: pulumi-resource-xyz-v${{ inputs.version }}-*
+        path: dist
+        # Don't create a directory for each artifact
+        merge-multiple: true
+    - name: Download schema
+      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
+      with:
+        # Use a pattern to avoid failing if the artifact doesn't exist
+        pattern: schema-embed.*
+        # Avoid creating directories for each artifact
+        merge-multiple: true
+        path: dist
+    - name: Calculate checksums
+      working-directory: dist
+      run: shasum ./*.tar.gz > "pulumi-xyz_${{ inputs.version }}_checksums.txt"
+    - name: Get Schema Change Summary
+      id: schema-summary
+      shell: bash
+      run: |
+        # Get latest stable release. Return only first column from result (tag).
+        LAST_VERSION=$(gh release view --repo pulumi/pulumi-xyz --json tagName -q .tagName || echo "No stable release" )
+        {
+          echo 'summary<<EOF'
+          if [[ "$LAST_VERSION" != "No stable release" ]]; then
+            schema-tools compare --provider="xyz" --old-commit="$LAST_VERSION" --repository="github://api.github.com/pulumi" --new-commit="--local-path=provider/cmd/pulumi-resource-xyz/schema.json"
+          fi
+          echo 'EOF'
+        } >> "$GITHUB_OUTPUT"
+    - name: Create GH Release
+      uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
+      if: inputs.isPrerelease == false
+      with:
+        tag_name: v${{ inputs.version }}
+        prerelease: ${{ inputs.isPrerelease }}
+        # We keep pre-releases as drafts so they're not visible until we manually publish them.
+        draft: ${{ inputs.isPrerelease }}
+        # Explicitly set make_latest to account for backported releases
+        make_latest: ${{ inputs.setLatestRelease }}
+        body: ${{ steps.schema-summary.outputs.summary }}
+        generate_release_notes: true
+        files: dist/*
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   #publish_sdk:
   #  name: publish_sdk
